# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

index:
      pattern: /index/
      defaults: {_controller: AcmeShowStuff:ShowStuff:index}

adminboard:
      pattern: /adminboard/
      defaults: {_controller: AcmeShowStuff:AdminBoard:index}

editadminboard:
      pattern: /adminboard/{num}
      defaults: {_controller: AcmeShowStuff:AdminBoard:edit}

addcompany:
      pattern: /addcompany/
      defaults: {_controller: AcmeShowStuff:AdminBoard:addcompany}

createcompany:
      pattern: /createcompany/
      defaults: {_controller: AcmeShowStuff:AdminBoard:createcompany}

editcompany:
      pattern: /editcompany/{num}
      defaults: {_controller: AcmeShowStuff:AdminBoard:editforce}

deletecompany:
      pattern: /deletecompany/{num_id}
      defaults: {_controller: AcmeShowStuff:AdminBoard:deletecompany}
