# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

index:
      pattern: /index/
      defaults: {_controller: AcmeShowStuff:ShowStuff:index}

adminboard:
      pattern: /adminboard/
      defaults: {_controller: AcmeShowStuff:AdminBoard:index}

editadminboard:
      pattern: /adminboard/{num}
      defaults: {_controller: AcmeShowStuff:AdminBoard:edit}